version: "3.9"

services:
  mariadb:
    image: mariadb:10.4
    container_name: mariadb-db
    restart: unless-stopped
    ports:
      - "3320:3306"
    environment:
      MARIADB_ROOT_PASSWORD: dev
      MARIADB_DATABASE: myeeatsdb
    volumes:
      - db-data:/var/lib/mysql

volumes:
  db-data:
